[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      connect-src *;
      frame-src https://*.youtube.com https://youtube.com https://*.vimeo.com https://vimeo.com https://*.wistia.com https://wistia.com https://*.vidyard.com https://vidyard.com https://*.brightcove.net https://brightcove.net;
      frame-ancestors https://*.youtube.com https://youtube.com https://*.vimeo.com https://vimeo.com https://*.wistia.com https://wistia.com https://*.vidyard.com https://vidyard.com https://*.brightcove.net https://brightcove.net
    '''
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin"
    Permissions-Policy = "payment=(self)"

[[redirects]]
  from = "/client-api/*"
  to = "https://dev1-client-api-proxy.openchannel.io/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
