export enum ActionTypes {
  START_LOADING = '@user-types/START_LOADING',
  FINISH_LOADING = '@user-types/FINISH_LOADING',
  GET_USER_ACCOUNT = '@user-types/GET_USER_ACCOUNT',
  GET_USER_CONFIG = '@user-types/GET_USER_CONFIG',
  GET_USER_COMPANY_FORM = '@user-types/GET_USER_COMPANY_FORM',
  RESET_USER_COMPANY_FORM = '@user-types/RESET_USER_COMPANY_FORM',
}
